create extension if not exists pgcrypto;

create table if not exists public.profiles (
 user_id uuid primary key references auth.users(id) on delete cascade,
 name text, role text not null default 'user', preferences jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.workspaces (
 id uuid primary key default gen_random_uuid(), name text not null default 'POWER SCALE', slug text unique,
 settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.workspace_members (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'owner', active boolean not null default true,
 created_at timestamptz not null default now(), unique(workspace_id,user_id)
);
create table if not exists public.platforms (
 id bigint generated by default as identity primary key, workspace_id uuid references public.workspaces(id) on delete cascade,
 name text not null, slug text, logo_url text, active boolean not null default true, payload jsonb not null default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.user_platforms (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade, platform_id bigint references public.platforms(id) on delete cascade,
 credentials jsonb not null default '{}'::jsonb, active boolean default true, created_at timestamptz default now(), unique(workspace_id,user_id,platform_id)
);
create table if not exists public.trackers (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 uuid uuid not null default gen_random_uuid(), name text not null, platform_id bigint references public.platforms(id), pixel text, pixel_checkout text,
 checkout_type text default 'standard', checkout_url_match text, script_type text default 'full_tracker', mining_status text,
 archived_at timestamptz, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,uuid)
);
create table if not exists public.tracker_scroll_events (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 tracker_id bigint not null references public.trackers(id) on delete cascade, visitor_id text, depth numeric, path text, occurred_at timestamptz default now(), payload jsonb default '{}'::jsonb
);
create table if not exists public.domains (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 domain text not null, status text default 'pending', verified_at timestamptz, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,domain)
);
create table if not exists public.sites (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 domain_id bigint references public.domains(id), tracker_id bigint references public.trackers(id), type text, name text, subdomain text, slug text,
 aff_link text, accept_language text, active boolean default true, prompt text, source_url text, source_text text, style_url text, style_text text,
 images jsonb default '[]'::jsonb, scraped_images jsonb default '[]'::jsonb, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.site_captures (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 site_id bigint references public.sites(id) on delete cascade, status text, storage_path text, payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.visitor_sessions (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 tracker_id bigint references public.trackers(id), visitor_key text, session_key text, url text, referrer text, ip_hash text, user_agent text,
 country text, region text, city text, device text, browser text, os text, started_at timestamptz default now(), ended_at timestamptz,
 payload jsonb default '{}'::jsonb
);
create table if not exists public.visitor_events (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 session_id bigint not null references public.visitor_sessions(id) on delete cascade, event_type text not null, occurred_at timestamptz default now(), payload jsonb default '{}'::jsonb
);
create table if not exists public.visitor_replays (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 session_id bigint not null references public.visitor_sessions(id) on delete cascade, replay jsonb not null default '[]'::jsonb, created_at timestamptz default now()
);
create table if not exists public.visitor_insights (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 session_id bigint not null references public.visitor_sessions(id) on delete cascade, insight text, payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.canvas_views (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.google_accounts (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid references auth.users(id), external_id text, email text, name text, refresh_token_encrypted text, status text default 'active', payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,external_id)
);
create table if not exists public.google_ads_accounts (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 google_account_id bigint references public.google_accounts(id) on delete cascade, external_id text not null, name text, currency_code text, timezone text,
 manager boolean default false, status text default 'active', sync_enabled boolean default true, source text default 'api', payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,external_id)
);
create table if not exists public.google_ads_campaigns (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 account_id bigint not null references public.google_ads_accounts(id) on delete cascade, external_id text not null, name text not null, status text,
 validation_status text, tracker_id bigint references public.trackers(id) on delete set null, advertising_channel_type text, payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,account_id,external_id)
);
create table if not exists public.google_ads_daily_metrics (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 account_id bigint references public.google_ads_accounts(id) on delete cascade, campaign_id bigint not null references public.google_ads_campaigns(id) on delete cascade,
 metric_date date not null, impressions bigint default 0, clicks bigint default 0, cost numeric(18,6) default 0, conversions numeric(18,6) default 0,
 conversion_value numeric(18,6) default 0, checkout_conversions numeric(18,6) default 0, checkout_value numeric(18,6) default 0,
 all_conversions numeric(18,6) default 0, all_conversion_value numeric(18,6) default 0, view_through_conversions numeric(18,6) default 0,
 cross_device_conversions numeric(18,6) default 0, average_cpc numeric(18,6), average_cpm numeric(18,6), ctr_percent numeric(18,6),
 impression_share_percent numeric(18,6), top_impression_share_percent numeric(18,6), absolute_top_impression_share_percent numeric(18,6),
 search_rank_lost_is_percent numeric(18,6), search_rank_lost_top_is_percent numeric(18,6), search_rank_lost_abs_top_is_percent numeric(18,6),
 search_budget_lost_is_percent numeric(18,6), search_budget_lost_top_is_percent numeric(18,6), search_budget_lost_abs_top_is_percent numeric(18,6),
 search_eligible_top_is_percent numeric(18,6), search_eligible_abs_top_is_percent numeric(18,6), search_exact_match_is_percent numeric(18,6),
 search_click_share_percent numeric(18,6), interactions bigint, interaction_rate_percent numeric(18,6), invalid_clicks bigint, invalid_click_rate_percent numeric(18,6),
 average_cost numeric(18,6), engagements bigint, engagement_rate numeric(18,6), active_view_impressions bigint, active_view_measurability numeric(18,6),
 active_view_viewability numeric(18,6), gmail_forwards bigint, gmail_saves bigint, gmail_secondary_clicks bigint,
 payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(campaign_id,metric_date)
);
create table if not exists public.google_ads_segments (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 campaign_id bigint references public.google_ads_campaigns(id) on delete cascade, segment_date date, segment_type text not null, segment_key text not null,
 dimension jsonb not null default '{}'::jsonb, impressions bigint default 0, clicks bigint default 0, cost numeric(18,6) default 0, conversions numeric(18,6) default 0,
 conversion_value numeric(18,6) default 0, checkout_conversions numeric(18,6) default 0, checkout_value numeric(18,6) default 0,
 all_conversions numeric(18,6) default 0, all_conversion_value numeric(18,6) default 0, view_through_conversions numeric(18,6) default 0,
 cross_device_conversions numeric(18,6) default 0, average_cpc numeric(18,6), average_cpm numeric(18,6), ctr_percent numeric(18,6),
 impression_share_percent numeric(18,6), top_impression_share_percent numeric(18,6), absolute_top_impression_share_percent numeric(18,6),
 search_rank_lost_is_percent numeric(18,6), search_rank_lost_top_is_percent numeric(18,6), search_rank_lost_abs_top_is_percent numeric(18,6),
 search_budget_lost_is_percent numeric(18,6), search_budget_lost_top_is_percent numeric(18,6), search_budget_lost_abs_top_is_percent numeric(18,6),
 search_eligible_top_is_percent numeric(18,6), search_eligible_abs_top_is_percent numeric(18,6), search_exact_match_is_percent numeric(18,6), search_click_share_percent numeric(18,6),
 interactions bigint, interaction_rate_percent numeric(18,6), invalid_clicks bigint, invalid_click_rate_percent numeric(18,6), average_cost numeric(18,6), engagements bigint,
 engagement_rate numeric(18,6), active_view_impressions bigint, active_view_measurability numeric(18,6), active_view_viewability numeric(18,6), gmail_forwards bigint,
 gmail_saves bigint, gmail_secondary_clicks bigint, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(),
 unique(campaign_id,segment_date,segment_type,segment_key)
);
create table if not exists public.google_ads_integrations (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 integration_type text, status text, message text, payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.google_ads_kanban_rules (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text, rules jsonb not null default '{}'::jsonb, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.google_ads_daily_notes (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 campaign_id bigint not null references public.google_ads_campaigns(id) on delete cascade, note_date date not null, note text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(campaign_id,note_date)
);
create table if not exists public.google_ads_daily_overrides (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 campaign_id bigint not null references public.google_ads_campaigns(id) on delete cascade, override_date date not null, values jsonb not null default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(campaign_id,override_date)
);
create table if not exists public.google_ads_sync_logs (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 account_id bigint references public.google_ads_accounts(id), status text, started_at timestamptz default now(), finished_at timestamptz, payload jsonb default '{}'::jsonb
);
create table if not exists public.financial_categories (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, type text, active boolean default true, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.financial_entries (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 category_id bigint references public.financial_categories(id), entry_date date not null default current_date, type text not null, description text,
 amount numeric(18,6) not null default 0, currency text default 'USD', recurring boolean default false, payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.financial_company_settings (
 workspace_id uuid primary key references public.workspaces(id) on delete cascade, settings jsonb not null default '{}'::jsonb, updated_at timestamptz default now()
);
create table if not exists public.financial_mining (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, platform text, country text, currency text default 'USD', cpc numeric(18,6), commission numeric(18,6), notes text, status text default 'research',
 tracker_id bigint references public.trackers(id), payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.financial_viability_settings (
 workspace_id uuid primary key references public.workspaces(id) on delete cascade, settings jsonb not null default '{}'::jsonb, updated_at timestamptz default now()
);

create index if not exists idx_trackers_ws on public.trackers(workspace_id);
create index if not exists idx_visitors_ws_started on public.visitor_sessions(workspace_id,started_at desc);
create index if not exists idx_campaigns_ws_account on public.google_ads_campaigns(workspace_id,account_id);
create index if not exists idx_metrics_campaign_date on public.google_ads_daily_metrics(campaign_id,metric_date desc);
create index if not exists idx_segments_campaign_date on public.google_ads_segments(campaign_id,segment_date desc);
create index if not exists idx_fin_entries_ws_date on public.financial_entries(workspace_id,entry_date desc);


-- POWER SCALE Apps Script raw ingestion
create table if not exists public.google_ads_import_rows (
 id bigint generated by default as identity primary key,
 row_key text,
 workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid references auth.users(id) on delete set null,
 account_external_id text,
 campaign_external_id text,
 segment_type text not null,
 segment_date date,
 segment_key text,
 ad_group_external_id text,
 dimension jsonb not null default '{}'::jsonb,
 payload jsonb not null default '{}'::jsonb,
 imported_at timestamptz default now(),
 created_at timestamptz default now()
);
create index if not exists idx_google_ads_import_rows_ws_date on public.google_ads_import_rows(workspace_id,segment_date desc);
create index if not exists idx_google_ads_import_rows_campaign on public.google_ads_import_rows(workspace_id,campaign_external_id,segment_date desc);
create index if not exists idx_google_ads_import_rows_segment on public.google_ads_import_rows(workspace_id,segment_type,segment_date desc);


-- POWER SCALE v9 migration: safe upgrades for existing v8 databases
alter table public.google_ads_import_rows add column if not exists row_key text;
alter table public.google_ads_import_rows add column if not exists segment_key text;
alter table public.google_ads_import_rows add column if not exists ad_group_external_id text;
alter table public.google_ads_import_rows add column if not exists dimension jsonb not null default '{}'::jsonb;
create unique index if not exists uq_google_ads_import_rows_workspace_row_key on public.google_ads_import_rows(workspace_id,row_key);

alter table public.google_ads_segments add column if not exists dimension jsonb not null default '{}'::jsonb;
alter table public.google_ads_segments add column if not exists checkout_conversions numeric(18,6) default 0;
alter table public.google_ads_segments add column if not exists checkout_value numeric(18,6) default 0;
alter table public.google_ads_segments add column if not exists all_conversions numeric(18,6) default 0;
alter table public.google_ads_segments add column if not exists all_conversion_value numeric(18,6) default 0;
alter table public.google_ads_segments add column if not exists view_through_conversions numeric(18,6) default 0;
alter table public.google_ads_segments add column if not exists cross_device_conversions numeric(18,6) default 0;
alter table public.google_ads_segments add column if not exists average_cpc numeric(18,6);
alter table public.google_ads_segments add column if not exists average_cpm numeric(18,6);
alter table public.google_ads_segments add column if not exists ctr_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists impression_share_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists top_impression_share_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists absolute_top_impression_share_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_rank_lost_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_rank_lost_top_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_rank_lost_abs_top_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_budget_lost_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_budget_lost_top_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_budget_lost_abs_top_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_eligible_top_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_eligible_abs_top_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_exact_match_is_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists search_click_share_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists interactions bigint;
alter table public.google_ads_segments add column if not exists interaction_rate_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists invalid_clicks bigint;
alter table public.google_ads_segments add column if not exists invalid_click_rate_percent numeric(18,6);
alter table public.google_ads_segments add column if not exists average_cost numeric(18,6);
alter table public.google_ads_segments add column if not exists engagements bigint;
alter table public.google_ads_segments add column if not exists engagement_rate numeric(18,6);
alter table public.google_ads_segments add column if not exists active_view_impressions bigint;
alter table public.google_ads_segments add column if not exists active_view_measurability numeric(18,6);
alter table public.google_ads_segments add column if not exists active_view_viewability numeric(18,6);
alter table public.google_ads_segments add column if not exists gmail_forwards bigint;
alter table public.google_ads_segments add column if not exists gmail_saves bigint;
alter table public.google_ads_segments add column if not exists gmail_secondary_clicks bigint;
alter table public.google_ads_segments add column if not exists updated_at timestamptz default now();
create unique index if not exists uq_google_ads_segments_dimension on public.google_ads_segments(campaign_id,segment_date,segment_type,segment_key);

alter table public.google_ads_daily_metrics add column if not exists checkout_value numeric(18,6) default 0;
alter table public.google_ads_daily_metrics add column if not exists all_conversion_value numeric(18,6) default 0;
alter table public.google_ads_daily_metrics add column if not exists view_through_conversions numeric(18,6) default 0;
alter table public.google_ads_daily_metrics add column if not exists cross_device_conversions numeric(18,6) default 0;
alter table public.google_ads_daily_metrics add column if not exists average_cpc numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists average_cpm numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists ctr_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists impression_share_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists top_impression_share_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists absolute_top_impression_share_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_rank_lost_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_rank_lost_top_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_rank_lost_abs_top_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_budget_lost_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_budget_lost_top_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_budget_lost_abs_top_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_eligible_top_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_eligible_abs_top_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_exact_match_is_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists search_click_share_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists interactions bigint;
alter table public.google_ads_daily_metrics add column if not exists interaction_rate_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists invalid_clicks bigint;
alter table public.google_ads_daily_metrics add column if not exists invalid_click_rate_percent numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists average_cost numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists engagements bigint;
alter table public.google_ads_daily_metrics add column if not exists engagement_rate numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists active_view_impressions bigint;
alter table public.google_ads_daily_metrics add column if not exists active_view_measurability numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists active_view_viewability numeric(18,6);
alter table public.google_ads_daily_metrics add column if not exists gmail_forwards bigint;
alter table public.google_ads_daily_metrics add column if not exists gmail_saves bigint;
alter table public.google_ads_daily_metrics add column if not exists gmail_secondary_clicks bigint;

-- v9: campaign IDs are scoped to a Google Ads account
alter table public.google_ads_campaigns drop constraint if exists google_ads_campaigns_workspace_id_external_id_key;
create unique index if not exists uq_google_ads_campaigns_workspace_account_external on public.google_ads_campaigns(workspace_id,account_id,external_id);


-- v13 product identification rules
-- POWER SCALE v13
-- Execute uma vez no SQL Editor do Supabase antes do deploy da v13.

create unique index if not exists uq_platforms_workspace_slug on public.platforms(workspace_id,slug);

create table if not exists public.product_identification_rules (
 id bigint generated by default as identity primary key,
 workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, priority integer not null default 100,
 rule_type text not null check (rule_type in ('bracket_position','contains','starts_with','ends_with','regex')),
 pattern text not null default '', position integer,
 result_mode text not null default 'extract' check (result_mode in ('extract','fixed')),
 result_value text, result_case text not null default 'title' check (result_case in ('keep','upper','lower','title')),
 case_sensitive boolean not null default false, trim_result boolean not null default true,
 action text not null default 'suggest' check (action in ('suggest','create','create_link')),
 active boolean not null default true, payload jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_product_rules_workspace_priority on public.product_identification_rules(workspace_id,priority,id);

