create extension if not exists pgcrypto;

create table if not exists public.profiles (
 user_id uuid primary key references auth.users(id) on delete cascade,
 name text, role text not null default 'user', preferences jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.workspaces (
 id uuid primary key default gen_random_uuid(), name text not null default 'POWER SCALE', slug text unique,
 settings jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.workspace_members (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid not null references auth.users(id) on delete cascade, role text not null default 'owner', active boolean not null default true,
 created_at timestamptz not null default now(), unique(workspace_id,user_id)
);
create table if not exists public.platforms (
 id bigint generated by default as identity primary key, workspace_id uuid references public.workspaces(id) on delete cascade,
 name text not null, slug text, logo_url text, active boolean not null default true, payload jsonb not null default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.user_platforms (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid references auth.users(id) on delete cascade, platform_id bigint references public.platforms(id) on delete cascade,
 credentials jsonb not null default '{}'::jsonb, active boolean default true, created_at timestamptz default now(), unique(workspace_id,user_id,platform_id)
);
create table if not exists public.trackers (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 uuid uuid not null default gen_random_uuid(), name text not null, platform_id bigint references public.platforms(id), pixel text, pixel_checkout text,
 checkout_type text default 'standard', checkout_url_match text, script_type text default 'full_tracker', mining_status text,
 archived_at timestamptz, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,uuid)
);
create table if not exists public.tracker_scroll_events (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 tracker_id bigint not null references public.trackers(id) on delete cascade, visitor_id text, depth numeric, path text, occurred_at timestamptz default now(), payload jsonb default '{}'::jsonb
);
create table if not exists public.domains (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 domain text not null, status text default 'pending', verified_at timestamptz, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,domain)
);
create table if not exists public.sites (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 domain_id bigint references public.domains(id), tracker_id bigint references public.trackers(id), type text, name text, subdomain text, slug text,
 aff_link text, accept_language text, active boolean default true, prompt text, source_url text, source_text text, style_url text, style_text text,
 images jsonb default '[]'::jsonb, scraped_images jsonb default '[]'::jsonb, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.site_captures (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 site_id bigint references public.sites(id) on delete cascade, status text, storage_path text, payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.visitor_sessions (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 tracker_id bigint references public.trackers(id), visitor_key text, session_key text, url text, referrer text, ip_hash text, user_agent text,
 country text, region text, city text, device text, browser text, os text, started_at timestamptz default now(), ended_at timestamptz,
 payload jsonb default '{}'::jsonb
);
create table if not exists public.visitor_events (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 session_id bigint not null references public.visitor_sessions(id) on delete cascade, event_type text not null, occurred_at timestamptz default now(), payload jsonb default '{}'::jsonb
);
create table if not exists public.visitor_replays (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 session_id bigint not null references public.visitor_sessions(id) on delete cascade, replay jsonb not null default '[]'::jsonb, created_at timestamptz default now()
);
create table if not exists public.visitor_insights (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 session_id bigint not null references public.visitor_sessions(id) on delete cascade, insight text, payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.canvas_views (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, payload jsonb not null default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.google_accounts (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 user_id uuid references auth.users(id), external_id text, email text, name text, refresh_token_encrypted text, status text default 'active', payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,external_id)
);
create table if not exists public.google_ads_accounts (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 google_account_id bigint references public.google_accounts(id) on delete cascade, external_id text not null, name text, currency_code text, timezone text,
 manager boolean default false, status text default 'active', sync_enabled boolean default true, source text default 'api', payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,external_id)
);
create table if not exists public.google_ads_campaigns (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 account_id bigint not null references public.google_ads_accounts(id) on delete cascade, external_id text not null, name text not null, status text,
 validation_status text, tracker_id bigint references public.trackers(id) on delete set null, advertising_channel_type text, payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(workspace_id,external_id)
);
create table if not exists public.google_ads_daily_metrics (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 account_id bigint references public.google_ads_accounts(id) on delete cascade, campaign_id bigint not null references public.google_ads_campaigns(id) on delete cascade,
 metric_date date not null, impressions bigint default 0, clicks bigint default 0, cost numeric(18,6) default 0, conversions numeric(18,6) default 0,
 conversion_value numeric(18,6) default 0, checkout_conversions numeric(18,6) default 0, all_conversions numeric(18,6) default 0,
 payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now(), unique(campaign_id,metric_date)
);
create table if not exists public.google_ads_segments (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 campaign_id bigint references public.google_ads_campaigns(id) on delete cascade, segment_date date, segment_type text not null, segment_key text,
 impressions bigint default 0, clicks bigint default 0, cost numeric(18,6) default 0, conversions numeric(18,6) default 0, conversion_value numeric(18,6) default 0,
 payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.google_ads_integrations (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 integration_type text, status text, message text, payload jsonb default '{}'::jsonb, created_at timestamptz default now()
);
create table if not exists public.google_ads_kanban_rules (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text, rules jsonb not null default '{}'::jsonb, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.google_ads_daily_notes (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 campaign_id bigint not null references public.google_ads_campaigns(id) on delete cascade, note_date date not null, note text, created_at timestamptz default now(), updated_at timestamptz default now(), unique(campaign_id,note_date)
);
create table if not exists public.google_ads_daily_overrides (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 campaign_id bigint not null references public.google_ads_campaigns(id) on delete cascade, override_date date not null, values jsonb not null default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now(), unique(campaign_id,override_date)
);
create table if not exists public.google_ads_sync_logs (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 account_id bigint references public.google_ads_accounts(id), status text, started_at timestamptz default now(), finished_at timestamptz, payload jsonb default '{}'::jsonb
);
create table if not exists public.financial_categories (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, type text, active boolean default true, payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.financial_entries (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 category_id bigint references public.financial_categories(id), entry_date date not null default current_date, type text not null, description text,
 amount numeric(18,6) not null default 0, currency text default 'USD', recurring boolean default false, payload jsonb default '{}'::jsonb,
 created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.financial_company_settings (
 workspace_id uuid primary key references public.workspaces(id) on delete cascade, settings jsonb not null default '{}'::jsonb, updated_at timestamptz default now()
);
create table if not exists public.financial_mining (
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, platform text, country text, currency text default 'USD', cpc numeric(18,6), commission numeric(18,6), notes text, status text default 'research',
 tracker_id bigint references public.trackers(id), payload jsonb default '{}'::jsonb, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.financial_viability_settings (
 workspace_id uuid primary key references public.workspaces(id) on delete cascade, settings jsonb not null default '{}'::jsonb, updated_at timestamptz default now()
);

create index if not exists idx_trackers_ws on public.trackers(workspace_id);
create index if not exists idx_visitors_ws_started on public.visitor_sessions(workspace_id,started_at desc);
create index if not exists idx_campaigns_ws_account on public.google_ads_campaigns(workspace_id,account_id);
create index if not exists idx_metrics_campaign_date on public.google_ads_daily_metrics(campaign_id,metric_date desc);
create index if not exists idx_segments_campaign_date on public.google_ads_segments(campaign_id,segment_date desc);
create index if not exists idx_fin_entries_ws_date on public.financial_entries(workspace_id,entry_date desc);
