-- POWER SCALE v13
-- Execute uma vez no SQL Editor do Supabase antes do deploy da v13.

create unique index if not exists uq_platforms_workspace_slug on public.platforms(workspace_id,slug);

create table if not exists public.product_identification_rules (
 id bigint generated by default as identity primary key,
 workspace_id uuid not null references public.workspaces(id) on delete cascade,
 name text not null, priority integer not null default 100,
 rule_type text not null check (rule_type in ('bracket_position','contains','starts_with','ends_with','regex')),
 pattern text not null default '', position integer,
 result_mode text not null default 'extract' check (result_mode in ('extract','fixed')),
 result_value text, result_case text not null default 'title' check (result_case in ('keep','upper','lower','title')),
 case_sensitive boolean not null default false, trim_result boolean not null default true,
 action text not null default 'suggest' check (action in ('suggest','create','create_link')),
 active boolean not null default true, payload jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists idx_product_rules_workspace_priority on public.product_identification_rules(workspace_id,priority,id);

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('platform-logos','platform-logos',true,2097152,array['image/png','image/jpeg','image/webp','image/svg+xml'])
on conflict(id) do update set public=true,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

with seeds(name,slug,logo_url) as (values
  ('AdCombo','adcombo','/platform-logos/adcombo.png'),
  ('Braip','braip','/platform-logos/braip.png'),
  ('BuyGoods','buygoods','/platform-logos/buygoods.png'),
  ('Cartpanda','cartpanda','/platform-logos/cartpanda.png'),
  ('ClickBank','clickbank','/platform-logos/clickbank.png'),
  ('ClicksADV','clicksadv','/platform-logos/clicksadv.png'),
  ('CPAgetti','cpagetti','/platform-logos/cpagetti.png'),
  ('Digistore','digistore','/platform-logos/digistore.png'),
  ('Dr. Cash','dr-cash','/platform-logos/dr-cash.png'),
  ('Gurumedia','gurumedia','/platform-logos/gurumedia.png'),
  ('Hotmart','hotmart','/platform-logos/hotmart.png'),
  ('Jvzoo','jvzoo','/platform-logos/jvzoo.png'),
  ('Kiwify','kiwify','/platform-logos/kiwify.png'),
  ('LemonAd','lemonad','/platform-logos/lemonad.png'),
  ('MaxWeb','maxweb','/platform-logos/maxweb.png'),
  ('MediaScalers','mediascalers','/platform-logos/mediascalers.png'),
  ('Monetizze','monetizze','/platform-logos/monetizze.png'),
  ('NutriProfits','nutriprofits','/platform-logos/nutriprofits.png'),
  ('ProfitPay','profitpay','/platform-logos/profitpay.png'),
  ('SellHealth','sellhealth','/platform-logos/sellhealth.png'),
  ('SmartADV','smartadv','/platform-logos/smartadv.png'),
  ('SmashLoud','smashloud','/platform-logos/smashloud.png'),
  ('TerraLeads','terraleads','/platform-logos/terraleads.png'),
  ('The Fellas Ads','the-fellas-ads','/platform-logos/the-fellas-ads.png'),
  ('Ticto','ticto','/platform-logos/ticto.png'),
  ('Traffic Light','traffic-light','/platform-logos/traffic-light.png'),
  ('Webvork','webvork','/platform-logos/webvork.png')
)
insert into public.platforms(workspace_id,name,slug,logo_url,active,payload)
select w.id,s.name,s.slug,s.logo_url,true,jsonb_build_object('seed','power-scale-v13') from public.workspaces w cross join seeds s
on conflict(workspace_id,slug) do update set name=excluded.name,logo_url=excluded.logo_url,active=true,updated_at=now();

-- Regra inicial segura: apenas sugere o 2º bloco entre colchetes.
insert into public.product_identification_rules(workspace_id,name,priority,rule_type,position,result_mode,result_case,action,active)
select w.id,'2º bloco entre colchetes',10,'bracket_position',2,'extract','title','suggest',true from public.workspaces w
where not exists(select 1 from public.product_identification_rules r where r.workspace_id=w.id);
